### ISSUE TITLE
Error when retrying

### ISSUE THREAD

**Issue by montovaneli** [opus-domini/fast-shot#11]
hello!

I am getting this error when trying to use retry in a POST with JSON Body:

```
request failed after 5 attempts: attempt 1: Post \"https://MYAPI.COM/send_msg\": EOF
attempt 2: Post \"https://MYAPI.COM/send_msg\": http: ContentLength=1663 with Body length 0
attempt 3: Post \"https://MYAPI.COM/send_msg\": http: ContentLength=1663 with Body length 0
attempt 4: Post \"https://MYAPI.COM/send_msg\": http: ContentLength=1663 with Body length 0
attempt 5: Post \"https://MYAPI.COM/send_msg\": http: ContentLength=1663 with Body length 0
```

It's worth mentioning that it works perfectly when the call doesn't fail, but in case a retry is needed, this happens.

My function:

```
func SendMsg(msg MsgData) error {

	resp, err := db.FastHttpClient.POST("/send_msg").Body().AsJSON(msg).Retry().SetExponentialBackoff(2*time.Second, 5, 2.0).Send()
	if err != nil {
		logger.Logger.Error("Error Response at SendMsg - " + err.Error())
		return err
	}
        defer resp.RawBody().Close()

	getBody, err := io.ReadAll(resp.RawBody())
	if err != nil {
		logger.Logger.Error("Error Response Body at SendMsg - " + err.Error())
		return err
	}

	sb := string(getBody)

	if resp.StatusCode() == 200 {
		return nil
	} else {
		logger.Logger.Error("Error Status Code at SendMsg - " + sb)
		return fmt.Errorf(sb)
	}
}
```

I also tried to change the chaining order to, but the error remains the same:
```
resp, err := db.FastHttpClient.POST("/send_msg").Retry().SetExponentialBackoff(2*time.Second, 5, 2.0).Body().AsJSON(msg).Send()
```

Maybe I'm doing something wrong?

Thanks in advance

**Comment by montovaneli** [comment]
Hmm, maybe the issue is that the request body is fully read during the first call to Do(). When retrying and calling Do() again, no data is read from the response body.

Maybe the executeWithRetry should generate the request on each attempt because of the nature of the body (io.Reader).

```
func (b *RequestBuilder) Send() (Response, error) {
	// Check for client validation errors
	if err := errors.Join(b.request.client.Validations().Unwrap()...); err != nil {
		return Response{}, errors.Join(errors.New(constant.ErrMsgClientValidation), err)
	}

	// Check for request validation errors
	if err := errors.Join(b.request.config.Validations().Unwrap()...); err != nil {
		return Response{}, errors.Join(errors.New(constant.ErrMsgRequestValidation), err)
	}
        
        // changed the order to not build the request before checks if it has retry config enabled

	// Check if maxAttempts are enabled
	if b.request.config.RetryConfig() != nil && b.request.config.RetryConfig().MaxAttempts() > 1 {
		return b.executeWithRetry() // changed this line because req will be constructed on each attempt
	}

	// Create request
	req, err := b.createHTTPRequest()
	if err != nil {
		return Response{}, errors.Join(errors.New(constant.ErrMsgCreateRequest), err)
	}

	// Execute the request
	return b.execute(req)
}
```

```
func (b *RequestBuilder) executeWithRetry() (Response, error) {
	var config = b.request.config.RetryConfig()
	var errExecution error
	var errAttempts []error
	var response Response

	for attempt := uint(0); attempt < config.MaxAttempts(); attempt++ {
		// Execute request on each attempt
		req, err := b.createHTTPRequest()
		if err != nil { 
			return Response{}, errors.Join(errors.New(constant.ErrMsgCreateRequest), err)
		} 
		response, errExecution = b.execute(req)
		//
		...
}
```

Of course you understand how fastshot works much better than me  😁
Can you please check if my thoughts are correct?

**Comment by hugo-andrade** [comment]
Hi @montovaneli! 

Thanks for the analysis. You are right, during the first `Do()` attempt, when I read the body, due to the nature of (io.Reader) I lose the information for the next attempts to `retry`.

I am currently working on a V2.0.0 in which I am rewriting the entire `response` part. One of the things I implemented was a wrapper for the body, in which I buffer the body for reuses during reads. 

I think that in the next days there will be something for this new version, but I will see if I can make a fix for the case you reported.

**Comment by montovaneli** [comment]
Nice, thank you so much for your work, fastshot is amazing and I'm using all over my projects.

If you want I can make a pull request with the discussed changes until the new release launch, just let me know.

**Comment by hugo-andrade** [comment]
Perfect! You are welcome to open a PR with the fix.

The new version will bring a more complete approach, but it would be good to have a fix so that other people who are using it can have this fix for now.

**Comment by montovaneli** [comment]
Done! Again, thank you for creating fastshot!
