### ISSUE TITLE
Error info lost in some request retries

### ISSUE THREAD

**Issue by neomantra** [opus-domini/fast-shot#3]
[In this code](https://github.com/opus-domini/fast-shot/blob/01aa532da2d71c02f5c517388f1faa277f73b5ff/request.go#L120)  for `RequestBuilder.executeWithRetry`:

```
	for i := 0; i < b.request.retries; i++ {
		// Execute request
		response, errExecution = b.execute(req)
		// Check for errors
		if errExecution == nil && !response.IsError() {
			return response, nil
		}
		// Append error
		errAttempts = append(errAttempts, fmt.Errorf("attempt %d: %w", i+1, errExecution))
		...
	}
```

In the case where `errExecution == nil` , but there `IsError`... then the wrapped `errExecution` will be `nil`.

After that, the `response` and any error related information will be lost to the caller.  Unwrapping it is unhelpful:
```
request failed after 1 attempts: attempt 1: %!w(<nil>)
```

One possible solution would be to restructure it to include the `Response.Status` :
```
		if errExecution == nil {
			if !response.IsError() {
				return response, nil
			}
			// One could also read the response body to see what the server sent...
			errExecution = fmt.Errorf("error response %s", response.Status())
		}
```

**Comment by hugo-andrade** [comment]
Hi @neomantra, good point! I will restructure to avoid this case.

Thanks for the collaboration!

**Comment by hugo-andrade** [comment]
Enhancement in new release [v0.8.3](https://github.com/opus-domini/fast-shot/releases/tag/v0.8.3)!
