### ISSUE TITLE
[Feature]: Support Client-Side Load-Balancing

### ISSUE THREAD

**Issue by levisyin** [opus-domini/fast-shot#4]
Nice work!

Can we add support for client-side LB, and providing commonly used integral LB algorithm(such as "Round-robin method", "Weighted round-robin method" and so on).

Also, it would be better if we can implement custom load balance algorithm.

Have a good day😀

**Comment by hugo-andrade** [comment]
Hi @levisyin!

Thank you for your feature suggestion!

I'm intrigued by the idea of adding client-side load balancing.

To better understand and prioritize this enhancement, could you provide some examples of use cases where these features would be particularly beneficial? Your insights will help in tailoring the implementation more effectively.

Best regards!

**Comment by levisyin** [comment]
Hi @hugo-andrade , thanks for your reply.

Our api server gateway need to implement load balancer function. So,  for gateway itself, this should be a "client-side" load balancer. If http client library already provide load balancer module, we can integrate it conveniently😀

**Comment by hugo-andrade** [comment]
Hi @levisyin, 

I'm working on a solution for this new feature, I'll bring good news and a new version soon 😄.

**Comment by hugo-andrade** [comment]
Hi @levisyin,

Take a look at the new version, [v0.9.0](https://github.com/opus-domini/fast-shot/releases/tag/v0.9.0)!

Fast Shot now support [Out-of-the-Box Support for Client Load Balancing](https://github.com/opus-domini/fast-shot?tab=readme-ov-file#out-of-the-box-support-for-client-load-balancing) 🚀

**Comment by levisyin** [comment]
@hugo-andrade Hi sir, is there a way for us to customize the LB algorithm?

**Comment by hugo-andrade** [comment]
I implemented it using Round Robin, would you have something in mind? Would you have any specific use case or examples to provide me?

**Comment by levisyin** [comment]
> I implemented it using Round Robin, would you have something in mind? Would you have any specific use case or examples to provide me?

Something like, provide a way for user to custom the lb when we call `fastshot.NewClientLoadBalancer`, such as
```golang
package main

type LoadBalancer func(context.Context, []string) string

func main() {
	randLB := func(ctx context.Context, endpoints []string) string {
		return endpoints[rand.Intn(len(endpoints))]

	}
	client := fastshot.NewClientLoadBalancer([]string{
		"https://api1.example.com",
		"https://api2.example.com",
		"https://api3.example.com",
	}, randLB).
		Config().SetTimeout(time.Second * 10).
		Build()
}
```

**Comment by levisyin** [comment]
Or maybe we can learn from https://github.com/luraproject/lura/tree/master/sd for a more powerful function
