### ISSUE TITLE
[Feature Request] support custom http clients

### ISSUE THREAD

**Issue by jmmills** [opus-domini/fast-shot#7]
It would be useful to have the ability to inject custom http client for use with the client builder pattern. Namely two use cases (a) mocking rather than httptest scenarios, and (b) using pre-constructed or instrumented http clients.

I have implemented this in https://github.com/opus-domini/fast-shot/pull/6

**Comment by hugo-andrade** [comment]
Hi @jmmills,

I liked the use cases mentioned, when I was implementing the first version I had even thought about going this route, but I hadn't matured the idea yet. I will review your PR, many thanks for your collaboration!

Best regards.

**Comment by hugo-andrade** [comment]
Hi @jmmills,

Feature Request released! Checkout [v0.10.0](https://github.com/opus-domini/fast-shot/releases/tag/v0.10.0).
